version: '1.0.{build}'

branches:
  only:
    - master

skip_non_tags: true

image: Visual Studio 2019

configuration:
  - Debug
  - Release

environment:
  matrix:
    - TOOLSET: msvc2019-x86
      GENERATOR: Visual Studio 16 2019
      PLATFORM: Win32
    - TOOLSET: msvc2019-x64
      GENERATOR: Visual Studio 16 2019
      PLATFORM: x64

matrix:
  fast_finish: true

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G "%GENERATOR%" -A %PLATFORM% -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%/zlib-%APPVEYOR_REPO_TAG_NAME%-%TOOLSET%-%CONFIGURATION% ..
  - cmd: cmake --build . --config %CONFIGURATION% --target INSTALL
  - cmd: cd ..
  - cmd: 7z a zlib-%APPVEYOR_REPO_TAG_NAME%-%TOOLSET%-%CONFIGURATION%.zip zlib-%APPVEYOR_REPO_TAG_NAME%-%TOOLSET%-%CONFIGURATION%\*

artifacts:
  - path: zlib-%APPVEYOR_REPO_TAG_NAME%-%TOOLSET%-%CONFIGURATION%.zip
    name: zlib

deploy:
  - provider: GitHub
    artifacts: /.*\.zip/
    auth_token:
      secure: V7tmaT1H61+mKEJT1uMzSVwT2HseGbOBhMHIBVWQ72YEprXQ0wyXWw3Cp9O4pvyR
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
